//COMMON PETS
const cPets = {
    bighorn: {
        name: "Bighorn",
        ID: "BH",
        variants: 4,
        rarity: "c",
        shinies: 1,
    },
    cro: {
        name: "Cro",
        ID: "CO",
        variants: 7,
        rarity: "c",
        shinies: 1,
    },
    flitter: {
        name: "Flitter",
        ID: "FL",
        variants: 7,
        rarity: "c",
        shinies: 1,
    },
    gekki: {
        name: "Pom",
        ID: "GK",
        variants: 9,
        rarity: "c",
        shinies: 1,
    },
    ghostfly: {
        name: "Ghostfly",
        ID: "GF",
        variants: 7,
        rarity: "c",
        shinies: 1,
    },
    mochi: {
        name: "Mochi",
        ID: "MC",
        variants: 8,
        rarity: "c",
        shinies: 1,
    },
    omp: {
        name: "Omp",
        ID: "OM",
        variants: 9,
        rarity: "c",
        shinies: 1,
    },
    pixci: {
        name: "Pixci",
        ID: "PX",
        variants: 8,
        rarity: "c",
        shinies: 1,
    },
    pom: {
        name: "Pom",
        ID: "PM",
        variants: 20,
        rarity: "c",
        shinies: 2,
    },
    pyrebird: {
        name: "Pyrebird",
        ID: "PY",
        variants: 8,
        rarity: "c",
        shinies: 1,
    },
    rockGuppy: {
        name: "Rock Guppy",
        ID: "RG",
        variants: 5,
        rarity: "c",
        shinies: 1,
    },
    seabun: {
        name: "Seabun",
        ID: "PY",
        variants: 10,
        rarity: "c",
        shinies: 1,
    },
    woolie: {
        name: "Woolie",
        ID: "WL",
        variants: 8,
        rarity: "c",
        shinies: 1,
    },
}

module.exports = cPets;